CREATE TABLE IF NOT EXISTS "levels" (
    "id" BIGINT PRIMARY KEY DEFAULT (SELECT * FROM levels WHERE id = (SELECT MAX(id) FROM levels);),
    "name" TEXT NOT NULL UNIQUE,
    "image" TEXT NOT NULL,
    "need_points" BIGINT NOT NULL UNIQUE,
    "level_number" BIGINT NOT NULL UNIQUE,
    "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000),
    "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)
);